// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"tail/internal/formatter"
)

// Ensure, that OutMock does implement formatter.Out.
// If this is not the case, regenerate this file with moq.
var _ formatter.Out = &OutMock{}

// OutMock is a mock implementation of formatter.Out.
//
//	func TestSomethingThatUsesOut(t *testing.T) {
//
//		// make and configure a mocked formatter.Out
//		mockedOut := &OutMock{
//			ClearScreenFunc: func() error {
//				panic("mock out the ClearScreen method")
//			},
//			ErrorFunc: func(buffer []string, err []string) error {
//				panic("mock out the Error method")
//			},
//			GetDefaultStyleFunc: func() (string, string, string) {
//				panic("mock out the GetDefaultStyle method")
//			},
//			PrintFunc: func() error {
//				panic("mock out the Print method")
//			},
//			PrintFullFunc: func(buffer []string) error {
//				panic("mock out the PrintFull method")
//			},
//			SetDataFunc: func(data []string)  {
//				panic("mock out the SetData method")
//			},
//			SetStatusFunc: func(status int) error {
//				panic("mock out the SetStatus method")
//			},
//		}
//
//		// use mockedOut in code that requires formatter.Out
//		// and then make assertions.
//
//	}
type OutMock struct {
	// ClearScreenFunc mocks the ClearScreen method.
	ClearScreenFunc func() error

	// ErrorFunc mocks the Error method.
	ErrorFunc func(buffer []string, err []string) error

	// GetDefaultStyleFunc mocks the GetDefaultStyle method.
	GetDefaultStyleFunc func() (string, string, string)

	// PrintFunc mocks the Print method.
	PrintFunc func() error

	// PrintFullFunc mocks the PrintFull method.
	PrintFullFunc func(buffer []string) error

	// SetDataFunc mocks the SetData method.
	SetDataFunc func(data []string)

	// SetStatusFunc mocks the SetStatus method.
	SetStatusFunc func(status int) error

	// calls tracks calls to the methods.
	calls struct {
		// ClearScreen holds details about calls to the ClearScreen method.
		ClearScreen []struct {
		}
		// Error holds details about calls to the Error method.
		Error []struct {
			// Buffer is the buffer argument value.
			Buffer []string
			// Err is the err argument value.
			Err []string
		}
		// GetDefaultStyle holds details about calls to the GetDefaultStyle method.
		GetDefaultStyle []struct {
		}
		// Print holds details about calls to the Print method.
		Print []struct {
		}
		// PrintFull holds details about calls to the PrintFull method.
		PrintFull []struct {
			// Buffer is the buffer argument value.
			Buffer []string
		}
		// SetData holds details about calls to the SetData method.
		SetData []struct {
			// Data is the data argument value.
			Data []string
		}
		// SetStatus holds details about calls to the SetStatus method.
		SetStatus []struct {
			// Status is the status argument value.
			Status int
		}
	}
	lockClearScreen     sync.RWMutex
	lockError           sync.RWMutex
	lockGetDefaultStyle sync.RWMutex
	lockPrint           sync.RWMutex
	lockPrintFull       sync.RWMutex
	lockSetData         sync.RWMutex
	lockSetStatus       sync.RWMutex
}

// ClearScreen calls ClearScreenFunc.
func (mock *OutMock) ClearScreen() error {
	if mock.ClearScreenFunc == nil {
		panic("OutMock.ClearScreenFunc: method is nil but Out.ClearScreen was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClearScreen.Lock()
	mock.calls.ClearScreen = append(mock.calls.ClearScreen, callInfo)
	mock.lockClearScreen.Unlock()
	return mock.ClearScreenFunc()
}

// ClearScreenCalls gets all the calls that were made to ClearScreen.
// Check the length with:
//
//	len(mockedOut.ClearScreenCalls())
func (mock *OutMock) ClearScreenCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClearScreen.RLock()
	calls = mock.calls.ClearScreen
	mock.lockClearScreen.RUnlock()
	return calls
}

// Error calls ErrorFunc.
func (mock *OutMock) Error(buffer []string, err []string) error {
	if mock.ErrorFunc == nil {
		panic("OutMock.ErrorFunc: method is nil but Out.Error was just called")
	}
	callInfo := struct {
		Buffer []string
		Err    []string
	}{
		Buffer: buffer,
		Err:    err,
	}
	mock.lockError.Lock()
	mock.calls.Error = append(mock.calls.Error, callInfo)
	mock.lockError.Unlock()
	return mock.ErrorFunc(buffer, err)
}

// ErrorCalls gets all the calls that were made to Error.
// Check the length with:
//
//	len(mockedOut.ErrorCalls())
func (mock *OutMock) ErrorCalls() []struct {
	Buffer []string
	Err    []string
} {
	var calls []struct {
		Buffer []string
		Err    []string
	}
	mock.lockError.RLock()
	calls = mock.calls.Error
	mock.lockError.RUnlock()
	return calls
}

// GetDefaultStyle calls GetDefaultStyleFunc.
func (mock *OutMock) GetDefaultStyle() (string, string, string) {
	if mock.GetDefaultStyleFunc == nil {
		panic("OutMock.GetDefaultStyleFunc: method is nil but Out.GetDefaultStyle was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetDefaultStyle.Lock()
	mock.calls.GetDefaultStyle = append(mock.calls.GetDefaultStyle, callInfo)
	mock.lockGetDefaultStyle.Unlock()
	return mock.GetDefaultStyleFunc()
}

// GetDefaultStyleCalls gets all the calls that were made to GetDefaultStyle.
// Check the length with:
//
//	len(mockedOut.GetDefaultStyleCalls())
func (mock *OutMock) GetDefaultStyleCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetDefaultStyle.RLock()
	calls = mock.calls.GetDefaultStyle
	mock.lockGetDefaultStyle.RUnlock()
	return calls
}

// Print calls PrintFunc.
func (mock *OutMock) Print() error {
	if mock.PrintFunc == nil {
		panic("OutMock.PrintFunc: method is nil but Out.Print was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPrint.Lock()
	mock.calls.Print = append(mock.calls.Print, callInfo)
	mock.lockPrint.Unlock()
	return mock.PrintFunc()
}

// PrintCalls gets all the calls that were made to Print.
// Check the length with:
//
//	len(mockedOut.PrintCalls())
func (mock *OutMock) PrintCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPrint.RLock()
	calls = mock.calls.Print
	mock.lockPrint.RUnlock()
	return calls
}

// PrintFull calls PrintFullFunc.
func (mock *OutMock) PrintFull(buffer []string) error {
	if mock.PrintFullFunc == nil {
		panic("OutMock.PrintFullFunc: method is nil but Out.PrintFull was just called")
	}
	callInfo := struct {
		Buffer []string
	}{
		Buffer: buffer,
	}
	mock.lockPrintFull.Lock()
	mock.calls.PrintFull = append(mock.calls.PrintFull, callInfo)
	mock.lockPrintFull.Unlock()
	return mock.PrintFullFunc(buffer)
}

// PrintFullCalls gets all the calls that were made to PrintFull.
// Check the length with:
//
//	len(mockedOut.PrintFullCalls())
func (mock *OutMock) PrintFullCalls() []struct {
	Buffer []string
} {
	var calls []struct {
		Buffer []string
	}
	mock.lockPrintFull.RLock()
	calls = mock.calls.PrintFull
	mock.lockPrintFull.RUnlock()
	return calls
}

// SetData calls SetDataFunc.
func (mock *OutMock) SetData(data []string) {
	if mock.SetDataFunc == nil {
		panic("OutMock.SetDataFunc: method is nil but Out.SetData was just called")
	}
	callInfo := struct {
		Data []string
	}{
		Data: data,
	}
	mock.lockSetData.Lock()
	mock.calls.SetData = append(mock.calls.SetData, callInfo)
	mock.lockSetData.Unlock()
	mock.SetDataFunc(data)
}

// SetDataCalls gets all the calls that were made to SetData.
// Check the length with:
//
//	len(mockedOut.SetDataCalls())
func (mock *OutMock) SetDataCalls() []struct {
	Data []string
} {
	var calls []struct {
		Data []string
	}
	mock.lockSetData.RLock()
	calls = mock.calls.SetData
	mock.lockSetData.RUnlock()
	return calls
}

// SetStatus calls SetStatusFunc.
func (mock *OutMock) SetStatus(status int) error {
	if mock.SetStatusFunc == nil {
		panic("OutMock.SetStatusFunc: method is nil but Out.SetStatus was just called")
	}
	callInfo := struct {
		Status int
	}{
		Status: status,
	}
	mock.lockSetStatus.Lock()
	mock.calls.SetStatus = append(mock.calls.SetStatus, callInfo)
	mock.lockSetStatus.Unlock()
	return mock.SetStatusFunc(status)
}

// SetStatusCalls gets all the calls that were made to SetStatus.
// Check the length with:
//
//	len(mockedOut.SetStatusCalls())
func (mock *OutMock) SetStatusCalls() []struct {
	Status int
} {
	var calls []struct {
		Status int
	}
	mock.lockSetStatus.RLock()
	calls = mock.calls.SetStatus
	mock.lockSetStatus.RUnlock()
	return calls
}
