// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"tail/internal/formatter/buffer/ansi"
	"tail/internal/formatter/buffer/parser"
)

// Ensure, that OtherListMock does implement parser.OtherList.
// If this is not the case, regenerate this file with moq.
var _ parser.OtherList = &OtherListMock{}

// OtherListMock is a mock implementation of parser.OtherList.
//
//	func TestSomethingThatUsesOtherList(t *testing.T) {
//
//		// make and configure a mocked parser.OtherList
//		mockedOtherList := &OtherListMock{
//			GetFunctionFunc: func(char rune) (func([]uint64) (ansi.Command, bool), bool) {
//				panic("mock out the GetFunction method")
//			},
//		}
//
//		// use mockedOtherList in code that requires parser.OtherList
//		// and then make assertions.
//
//	}
type OtherListMock struct {
	// GetFunctionFunc mocks the GetFunction method.
	GetFunctionFunc func(char rune) (func([]uint64) (ansi.Command, bool), bool)

	// calls tracks calls to the methods.
	calls struct {
		// GetFunction holds details about calls to the GetFunction method.
		GetFunction []struct {
			// Char is the char argument value.
			Char rune
		}
	}
	lockGetFunction sync.RWMutex
}

// GetFunction calls GetFunctionFunc.
func (mock *OtherListMock) GetFunction(char rune) (func([]uint64) (ansi.Command, bool), bool) {
	if mock.GetFunctionFunc == nil {
		panic("OtherListMock.GetFunctionFunc: method is nil but OtherList.GetFunction was just called")
	}
	callInfo := struct {
		Char rune
	}{
		Char: char,
	}
	mock.lockGetFunction.Lock()
	mock.calls.GetFunction = append(mock.calls.GetFunction, callInfo)
	mock.lockGetFunction.Unlock()
	return mock.GetFunctionFunc(char)
}

// GetFunctionCalls gets all the calls that were made to GetFunction.
// Check the length with:
//
//	len(mockedOtherList.GetFunctionCalls())
func (mock *OtherListMock) GetFunctionCalls() []struct {
	Char rune
} {
	var calls []struct {
		Char rune
	}
	mock.lockGetFunction.RLock()
	calls = mock.calls.GetFunction
	mock.lockGetFunction.RUnlock()
	return calls
}
