// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"tail/internal/formatter/buffer/ansi"
	"tail/internal/formatter/buffer/parser"
)

// Ensure, that WindowAndPalettesMock does implement parser.WindowAndPalettes.
// If this is not the case, regenerate this file with moq.
var _ parser.WindowAndPalettes = &WindowAndPalettesMock{}

// WindowAndPalettesMock is a mock implementation of parser.WindowAndPalettes.
//
//	func TestSomethingThatUsesWindowAndPalettes(t *testing.T) {
//
//		// make and configure a mocked parser.WindowAndPalettes
//		mockedWindowAndPalettes := &WindowAndPalettesMock{
//			GetFunctionFunc: func(char rune) (func([]uint64, string) (ansi.Command, bool), bool) {
//				panic("mock out the GetFunction method")
//			},
//		}
//
//		// use mockedWindowAndPalettes in code that requires parser.WindowAndPalettes
//		// and then make assertions.
//
//	}
type WindowAndPalettesMock struct {
	// GetFunctionFunc mocks the GetFunction method.
	GetFunctionFunc func(char rune) (func([]uint64, string) (ansi.Command, bool), bool)

	// calls tracks calls to the methods.
	calls struct {
		// GetFunction holds details about calls to the GetFunction method.
		GetFunction []struct {
			// Char is the char argument value.
			Char rune
		}
	}
	lockGetFunction sync.RWMutex
}

// GetFunction calls GetFunctionFunc.
func (mock *WindowAndPalettesMock) GetFunction(char rune) (func([]uint64, string) (ansi.Command, bool), bool) {
	if mock.GetFunctionFunc == nil {
		panic("WindowAndPalettesMock.GetFunctionFunc: method is nil but WindowAndPalettes.GetFunction was just called")
	}
	callInfo := struct {
		Char rune
	}{
		Char: char,
	}
	mock.lockGetFunction.Lock()
	mock.calls.GetFunction = append(mock.calls.GetFunction, callInfo)
	mock.lockGetFunction.Unlock()
	return mock.GetFunctionFunc(char)
}

// GetFunctionCalls gets all the calls that were made to GetFunction.
// Check the length with:
//
//	len(mockedWindowAndPalettes.GetFunctionCalls())
func (mock *WindowAndPalettesMock) GetFunctionCalls() []struct {
	Char rune
} {
	var calls []struct {
		Char rune
	}
	mock.lockGetFunction.RLock()
	calls = mock.calls.GetFunction
	mock.lockGetFunction.RUnlock()
	return calls
}
