// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"tail/internal/formatter"
)

// Ensure, that RenderMock does implement formatter.Render.
// If this is not the case, regenerate this file with moq.
var _ formatter.Render = &RenderMock{}

// RenderMock is a mock implementation of formatter.Render.
//
//	func TestSomethingThatUsesRender(t *testing.T) {
//
//		// make and configure a mocked formatter.Render
//		mockedRender := &RenderMock{
//			SetFunc: func(data string) error {
//				panic("mock out the Set method")
//			},
//			SetErrFunc: func(err error) error {
//				panic("mock out the SetErr method")
//			},
//			SetErrLineFunc: func(data string) error {
//				panic("mock out the SetErrLine method")
//			},
//			SetStatusFunc: func(status int) error {
//				panic("mock out the SetStatus method")
//			},
//		}
//
//		// use mockedRender in code that requires formatter.Render
//		// and then make assertions.
//
//	}
type RenderMock struct {
	// SetFunc mocks the Set method.
	SetFunc func(data string) error

	// SetErrFunc mocks the SetErr method.
	SetErrFunc func(err error) error

	// SetErrLineFunc mocks the SetErrLine method.
	SetErrLineFunc func(data string) error

	// SetStatusFunc mocks the SetStatus method.
	SetStatusFunc func(status int) error

	// calls tracks calls to the methods.
	calls struct {
		// Set holds details about calls to the Set method.
		Set []struct {
			// Data is the data argument value.
			Data string
		}
		// SetErr holds details about calls to the SetErr method.
		SetErr []struct {
			// Err is the err argument value.
			Err error
		}
		// SetErrLine holds details about calls to the SetErrLine method.
		SetErrLine []struct {
			// Data is the data argument value.
			Data string
		}
		// SetStatus holds details about calls to the SetStatus method.
		SetStatus []struct {
			// Status is the status argument value.
			Status int
		}
	}
	lockSet        sync.RWMutex
	lockSetErr     sync.RWMutex
	lockSetErrLine sync.RWMutex
	lockSetStatus  sync.RWMutex
}

// Set calls SetFunc.
func (mock *RenderMock) Set(data string) error {
	if mock.SetFunc == nil {
		panic("RenderMock.SetFunc: method is nil but Render.Set was just called")
	}
	callInfo := struct {
		Data string
	}{
		Data: data,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(data)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedRender.SetCalls())
func (mock *RenderMock) SetCalls() []struct {
	Data string
} {
	var calls []struct {
		Data string
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// SetErr calls SetErrFunc.
func (mock *RenderMock) SetErr(err error) error {
	if mock.SetErrFunc == nil {
		panic("RenderMock.SetErrFunc: method is nil but Render.SetErr was just called")
	}
	callInfo := struct {
		Err error
	}{
		Err: err,
	}
	mock.lockSetErr.Lock()
	mock.calls.SetErr = append(mock.calls.SetErr, callInfo)
	mock.lockSetErr.Unlock()
	return mock.SetErrFunc(err)
}

// SetErrCalls gets all the calls that were made to SetErr.
// Check the length with:
//
//	len(mockedRender.SetErrCalls())
func (mock *RenderMock) SetErrCalls() []struct {
	Err error
} {
	var calls []struct {
		Err error
	}
	mock.lockSetErr.RLock()
	calls = mock.calls.SetErr
	mock.lockSetErr.RUnlock()
	return calls
}

// SetErrLine calls SetErrLineFunc.
func (mock *RenderMock) SetErrLine(data string) error {
	if mock.SetErrLineFunc == nil {
		panic("RenderMock.SetErrLineFunc: method is nil but Render.SetErrLine was just called")
	}
	callInfo := struct {
		Data string
	}{
		Data: data,
	}
	mock.lockSetErrLine.Lock()
	mock.calls.SetErrLine = append(mock.calls.SetErrLine, callInfo)
	mock.lockSetErrLine.Unlock()
	return mock.SetErrLineFunc(data)
}

// SetErrLineCalls gets all the calls that were made to SetErrLine.
// Check the length with:
//
//	len(mockedRender.SetErrLineCalls())
func (mock *RenderMock) SetErrLineCalls() []struct {
	Data string
} {
	var calls []struct {
		Data string
	}
	mock.lockSetErrLine.RLock()
	calls = mock.calls.SetErrLine
	mock.lockSetErrLine.RUnlock()
	return calls
}

// SetStatus calls SetStatusFunc.
func (mock *RenderMock) SetStatus(status int) error {
	if mock.SetStatusFunc == nil {
		panic("RenderMock.SetStatusFunc: method is nil but Render.SetStatus was just called")
	}
	callInfo := struct {
		Status int
	}{
		Status: status,
	}
	mock.lockSetStatus.Lock()
	mock.calls.SetStatus = append(mock.calls.SetStatus, callInfo)
	mock.lockSetStatus.Unlock()
	return mock.SetStatusFunc(status)
}

// SetStatusCalls gets all the calls that were made to SetStatus.
// Check the length with:
//
//	len(mockedRender.SetStatusCalls())
func (mock *RenderMock) SetStatusCalls() []struct {
	Status int
} {
	var calls []struct {
		Status int
	}
	mock.lockSetStatus.RLock()
	calls = mock.calls.SetStatus
	mock.lockSetStatus.RUnlock()
	return calls
}
