// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"tail/internal/source/general"
)

// Ensure, that ScannerMock does implement general.Scanner.
// If this is not the case, regenerate this file with moq.
var _ general.Scanner = &ScannerMock{}

// ScannerMock is a mock implementation of general.Scanner.
//
//	func TestSomethingThatUsesScanner(t *testing.T) {
//
//		// make and configure a mocked general.Scanner
//		mockedScanner := &ScannerMock{
//			ErrFunc: func() <-chan string {
//				panic("mock out the Err method")
//			},
//			GetStatusFunc: func() (int, error) {
//				panic("mock out the GetStatus method")
//			},
//			OutFunc: func() <-chan string {
//				panic("mock out the Out method")
//			},
//		}
//
//		// use mockedScanner in code that requires general.Scanner
//		// and then make assertions.
//
//	}
type ScannerMock struct {
	// ErrFunc mocks the Err method.
	ErrFunc func() <-chan string

	// GetStatusFunc mocks the GetStatus method.
	GetStatusFunc func() (int, error)

	// OutFunc mocks the Out method.
	OutFunc func() <-chan string

	// calls tracks calls to the methods.
	calls struct {
		// Err holds details about calls to the Err method.
		Err []struct {
		}
		// GetStatus holds details about calls to the GetStatus method.
		GetStatus []struct {
		}
		// Out holds details about calls to the Out method.
		Out []struct {
		}
	}
	lockErr       sync.RWMutex
	lockGetStatus sync.RWMutex
	lockOut       sync.RWMutex
}

// Err calls ErrFunc.
func (mock *ScannerMock) Err() <-chan string {
	if mock.ErrFunc == nil {
		panic("ScannerMock.ErrFunc: method is nil but Scanner.Err was just called")
	}
	callInfo := struct {
	}{}
	mock.lockErr.Lock()
	mock.calls.Err = append(mock.calls.Err, callInfo)
	mock.lockErr.Unlock()
	return mock.ErrFunc()
}

// ErrCalls gets all the calls that were made to Err.
// Check the length with:
//
//	len(mockedScanner.ErrCalls())
func (mock *ScannerMock) ErrCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockErr.RLock()
	calls = mock.calls.Err
	mock.lockErr.RUnlock()
	return calls
}

// GetStatus calls GetStatusFunc.
func (mock *ScannerMock) GetStatus() (int, error) {
	if mock.GetStatusFunc == nil {
		panic("ScannerMock.GetStatusFunc: method is nil but Scanner.GetStatus was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetStatus.Lock()
	mock.calls.GetStatus = append(mock.calls.GetStatus, callInfo)
	mock.lockGetStatus.Unlock()
	return mock.GetStatusFunc()
}

// GetStatusCalls gets all the calls that were made to GetStatus.
// Check the length with:
//
//	len(mockedScanner.GetStatusCalls())
func (mock *ScannerMock) GetStatusCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetStatus.RLock()
	calls = mock.calls.GetStatus
	mock.lockGetStatus.RUnlock()
	return calls
}

// Out calls OutFunc.
func (mock *ScannerMock) Out() <-chan string {
	if mock.OutFunc == nil {
		panic("ScannerMock.OutFunc: method is nil but Scanner.Out was just called")
	}
	callInfo := struct {
	}{}
	mock.lockOut.Lock()
	mock.calls.Out = append(mock.calls.Out, callInfo)
	mock.lockOut.Unlock()
	return mock.OutFunc()
}

// OutCalls gets all the calls that were made to Out.
// Check the length with:
//
//	len(mockedScanner.OutCalls())
func (mock *ScannerMock) OutCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockOut.RLock()
	calls = mock.calls.Out
	mock.lockOut.RUnlock()
	return calls
}
