// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"tail/internal/sink/console/template/general"
)

// Ensure, that WindowMock does implement general.Window.
// If this is not the case, regenerate this file with moq.
var _ general.Window = &WindowMock{}

// WindowMock is a mock implementation of general.Window.
//
//	func TestSomethingThatUsesWindow(t *testing.T) {
//
//		// make and configure a mocked general.Window
//		mockedWindow := &WindowMock{
//			GetBufferSizeFunc: func() (uint64, uint64) {
//				panic("mock out the GetBufferSize method")
//			},
//			GetIconFunc: func() string {
//				panic("mock out the GetIcon method")
//			},
//			GetPositionFunc: func() (uint64, uint64) {
//				panic("mock out the GetPosition method")
//			},
//			GetTitleFunc: func() string {
//				panic("mock out the GetTitle method")
//			},
//		}
//
//		// use mockedWindow in code that requires general.Window
//		// and then make assertions.
//
//	}
type WindowMock struct {
	// GetBufferSizeFunc mocks the GetBufferSize method.
	GetBufferSizeFunc func() (uint64, uint64)

	// GetIconFunc mocks the GetIcon method.
	GetIconFunc func() string

	// GetPositionFunc mocks the GetPosition method.
	GetPositionFunc func() (uint64, uint64)

	// GetTitleFunc mocks the GetTitle method.
	GetTitleFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// GetBufferSize holds details about calls to the GetBufferSize method.
		GetBufferSize []struct {
		}
		// GetIcon holds details about calls to the GetIcon method.
		GetIcon []struct {
		}
		// GetPosition holds details about calls to the GetPosition method.
		GetPosition []struct {
		}
		// GetTitle holds details about calls to the GetTitle method.
		GetTitle []struct {
		}
	}
	lockGetBufferSize sync.RWMutex
	lockGetIcon       sync.RWMutex
	lockGetPosition   sync.RWMutex
	lockGetTitle      sync.RWMutex
}

// GetBufferSize calls GetBufferSizeFunc.
func (mock *WindowMock) GetBufferSize() (uint64, uint64) {
	if mock.GetBufferSizeFunc == nil {
		panic("WindowMock.GetBufferSizeFunc: method is nil but Window.GetBufferSize was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetBufferSize.Lock()
	mock.calls.GetBufferSize = append(mock.calls.GetBufferSize, callInfo)
	mock.lockGetBufferSize.Unlock()
	return mock.GetBufferSizeFunc()
}

// GetBufferSizeCalls gets all the calls that were made to GetBufferSize.
// Check the length with:
//
//	len(mockedWindow.GetBufferSizeCalls())
func (mock *WindowMock) GetBufferSizeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetBufferSize.RLock()
	calls = mock.calls.GetBufferSize
	mock.lockGetBufferSize.RUnlock()
	return calls
}

// GetIcon calls GetIconFunc.
func (mock *WindowMock) GetIcon() string {
	if mock.GetIconFunc == nil {
		panic("WindowMock.GetIconFunc: method is nil but Window.GetIcon was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetIcon.Lock()
	mock.calls.GetIcon = append(mock.calls.GetIcon, callInfo)
	mock.lockGetIcon.Unlock()
	return mock.GetIconFunc()
}

// GetIconCalls gets all the calls that were made to GetIcon.
// Check the length with:
//
//	len(mockedWindow.GetIconCalls())
func (mock *WindowMock) GetIconCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetIcon.RLock()
	calls = mock.calls.GetIcon
	mock.lockGetIcon.RUnlock()
	return calls
}

// GetPosition calls GetPositionFunc.
func (mock *WindowMock) GetPosition() (uint64, uint64) {
	if mock.GetPositionFunc == nil {
		panic("WindowMock.GetPositionFunc: method is nil but Window.GetPosition was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetPosition.Lock()
	mock.calls.GetPosition = append(mock.calls.GetPosition, callInfo)
	mock.lockGetPosition.Unlock()
	return mock.GetPositionFunc()
}

// GetPositionCalls gets all the calls that were made to GetPosition.
// Check the length with:
//
//	len(mockedWindow.GetPositionCalls())
func (mock *WindowMock) GetPositionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetPosition.RLock()
	calls = mock.calls.GetPosition
	mock.lockGetPosition.RUnlock()
	return calls
}

// GetTitle calls GetTitleFunc.
func (mock *WindowMock) GetTitle() string {
	if mock.GetTitleFunc == nil {
		panic("WindowMock.GetTitleFunc: method is nil but Window.GetTitle was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTitle.Lock()
	mock.calls.GetTitle = append(mock.calls.GetTitle, callInfo)
	mock.lockGetTitle.Unlock()
	return mock.GetTitleFunc()
}

// GetTitleCalls gets all the calls that were made to GetTitle.
// Check the length with:
//
//	len(mockedWindow.GetTitleCalls())
func (mock *WindowMock) GetTitleCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTitle.RLock()
	calls = mock.calls.GetTitle
	mock.lockGetTitle.RUnlock()
	return calls
}
