// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"tail/internal/sink/console/template/general"
)

// Ensure, that TemplateMock does implement general.Template.
// If this is not the case, regenerate this file with moq.
var _ general.Template = &TemplateMock{}

// TemplateMock is a mock implementation of general.Template.
//
//	func TestSomethingThatUsesTemplate(t *testing.T) {
//
//		// make and configure a mocked general.Template
//		mockedTemplate := &TemplateMock{
//			CleanLineFunc: func() string {
//				panic("mock out the CleanLine method")
//			},
//			EndLineFunc: func() string {
//				panic("mock out the EndLine method")
//			},
//			FormatLineFunc: func(line string) string {
//				panic("mock out the FormatLine method")
//			},
//			GetCellarFunc: func() string {
//				panic("mock out the GetCellar method")
//			},
//			GetCellarCleanFunc: func(b bool) string {
//				panic("mock out the GetCellarClean method")
//			},
//			GetHeaderFunc: func() string {
//				panic("mock out the GetHeader method")
//			},
//			GetHeaderCleanFunc: func(b bool) string {
//				panic("mock out the GetHeaderClean method")
//			},
//			StartLineFunc: func() string {
//				panic("mock out the StartLine method")
//			},
//		}
//
//		// use mockedTemplate in code that requires general.Template
//		// and then make assertions.
//
//	}
type TemplateMock struct {
	// CleanLineFunc mocks the CleanLine method.
	CleanLineFunc func() string

	// EndLineFunc mocks the EndLine method.
	EndLineFunc func() string

	// FormatLineFunc mocks the FormatLine method.
	FormatLineFunc func(line string) string

	// GetCellarFunc mocks the GetCellar method.
	GetCellarFunc func() string

	// GetCellarCleanFunc mocks the GetCellarClean method.
	GetCellarCleanFunc func(b bool) string

	// GetHeaderFunc mocks the GetHeader method.
	GetHeaderFunc func() string

	// GetHeaderCleanFunc mocks the GetHeaderClean method.
	GetHeaderCleanFunc func(b bool) string

	// StartLineFunc mocks the StartLine method.
	StartLineFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// CleanLine holds details about calls to the CleanLine method.
		CleanLine []struct {
		}
		// EndLine holds details about calls to the EndLine method.
		EndLine []struct {
		}
		// FormatLine holds details about calls to the FormatLine method.
		FormatLine []struct {
			// Line is the line argument value.
			Line string
		}
		// GetCellar holds details about calls to the GetCellar method.
		GetCellar []struct {
		}
		// GetCellarClean holds details about calls to the GetCellarClean method.
		GetCellarClean []struct {
			// B is the b argument value.
			B bool
		}
		// GetHeader holds details about calls to the GetHeader method.
		GetHeader []struct {
		}
		// GetHeaderClean holds details about calls to the GetHeaderClean method.
		GetHeaderClean []struct {
			// B is the b argument value.
			B bool
		}
		// StartLine holds details about calls to the StartLine method.
		StartLine []struct {
		}
	}
	lockCleanLine      sync.RWMutex
	lockEndLine        sync.RWMutex
	lockFormatLine     sync.RWMutex
	lockGetCellar      sync.RWMutex
	lockGetCellarClean sync.RWMutex
	lockGetHeader      sync.RWMutex
	lockGetHeaderClean sync.RWMutex
	lockStartLine      sync.RWMutex
}

// CleanLine calls CleanLineFunc.
func (mock *TemplateMock) CleanLine() string {
	if mock.CleanLineFunc == nil {
		panic("TemplateMock.CleanLineFunc: method is nil but Template.CleanLine was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCleanLine.Lock()
	mock.calls.CleanLine = append(mock.calls.CleanLine, callInfo)
	mock.lockCleanLine.Unlock()
	return mock.CleanLineFunc()
}

// CleanLineCalls gets all the calls that were made to CleanLine.
// Check the length with:
//
//	len(mockedTemplate.CleanLineCalls())
func (mock *TemplateMock) CleanLineCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCleanLine.RLock()
	calls = mock.calls.CleanLine
	mock.lockCleanLine.RUnlock()
	return calls
}

// EndLine calls EndLineFunc.
func (mock *TemplateMock) EndLine() string {
	if mock.EndLineFunc == nil {
		panic("TemplateMock.EndLineFunc: method is nil but Template.EndLine was just called")
	}
	callInfo := struct {
	}{}
	mock.lockEndLine.Lock()
	mock.calls.EndLine = append(mock.calls.EndLine, callInfo)
	mock.lockEndLine.Unlock()
	return mock.EndLineFunc()
}

// EndLineCalls gets all the calls that were made to EndLine.
// Check the length with:
//
//	len(mockedTemplate.EndLineCalls())
func (mock *TemplateMock) EndLineCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockEndLine.RLock()
	calls = mock.calls.EndLine
	mock.lockEndLine.RUnlock()
	return calls
}

// FormatLine calls FormatLineFunc.
func (mock *TemplateMock) FormatLine(line string) string {
	if mock.FormatLineFunc == nil {
		panic("TemplateMock.FormatLineFunc: method is nil but Template.FormatLine was just called")
	}
	callInfo := struct {
		Line string
	}{
		Line: line,
	}
	mock.lockFormatLine.Lock()
	mock.calls.FormatLine = append(mock.calls.FormatLine, callInfo)
	mock.lockFormatLine.Unlock()
	return mock.FormatLineFunc(line)
}

// FormatLineCalls gets all the calls that were made to FormatLine.
// Check the length with:
//
//	len(mockedTemplate.FormatLineCalls())
func (mock *TemplateMock) FormatLineCalls() []struct {
	Line string
} {
	var calls []struct {
		Line string
	}
	mock.lockFormatLine.RLock()
	calls = mock.calls.FormatLine
	mock.lockFormatLine.RUnlock()
	return calls
}

// GetCellar calls GetCellarFunc.
func (mock *TemplateMock) GetCellar() string {
	if mock.GetCellarFunc == nil {
		panic("TemplateMock.GetCellarFunc: method is nil but Template.GetCellar was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetCellar.Lock()
	mock.calls.GetCellar = append(mock.calls.GetCellar, callInfo)
	mock.lockGetCellar.Unlock()
	return mock.GetCellarFunc()
}

// GetCellarCalls gets all the calls that were made to GetCellar.
// Check the length with:
//
//	len(mockedTemplate.GetCellarCalls())
func (mock *TemplateMock) GetCellarCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetCellar.RLock()
	calls = mock.calls.GetCellar
	mock.lockGetCellar.RUnlock()
	return calls
}

// GetCellarClean calls GetCellarCleanFunc.
func (mock *TemplateMock) GetCellarClean(b bool) string {
	if mock.GetCellarCleanFunc == nil {
		panic("TemplateMock.GetCellarCleanFunc: method is nil but Template.GetCellarClean was just called")
	}
	callInfo := struct {
		B bool
	}{
		B: b,
	}
	mock.lockGetCellarClean.Lock()
	mock.calls.GetCellarClean = append(mock.calls.GetCellarClean, callInfo)
	mock.lockGetCellarClean.Unlock()
	return mock.GetCellarCleanFunc(b)
}

// GetCellarCleanCalls gets all the calls that were made to GetCellarClean.
// Check the length with:
//
//	len(mockedTemplate.GetCellarCleanCalls())
func (mock *TemplateMock) GetCellarCleanCalls() []struct {
	B bool
} {
	var calls []struct {
		B bool
	}
	mock.lockGetCellarClean.RLock()
	calls = mock.calls.GetCellarClean
	mock.lockGetCellarClean.RUnlock()
	return calls
}

// GetHeader calls GetHeaderFunc.
func (mock *TemplateMock) GetHeader() string {
	if mock.GetHeaderFunc == nil {
		panic("TemplateMock.GetHeaderFunc: method is nil but Template.GetHeader was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetHeader.Lock()
	mock.calls.GetHeader = append(mock.calls.GetHeader, callInfo)
	mock.lockGetHeader.Unlock()
	return mock.GetHeaderFunc()
}

// GetHeaderCalls gets all the calls that were made to GetHeader.
// Check the length with:
//
//	len(mockedTemplate.GetHeaderCalls())
func (mock *TemplateMock) GetHeaderCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetHeader.RLock()
	calls = mock.calls.GetHeader
	mock.lockGetHeader.RUnlock()
	return calls
}

// GetHeaderClean calls GetHeaderCleanFunc.
func (mock *TemplateMock) GetHeaderClean(b bool) string {
	if mock.GetHeaderCleanFunc == nil {
		panic("TemplateMock.GetHeaderCleanFunc: method is nil but Template.GetHeaderClean was just called")
	}
	callInfo := struct {
		B bool
	}{
		B: b,
	}
	mock.lockGetHeaderClean.Lock()
	mock.calls.GetHeaderClean = append(mock.calls.GetHeaderClean, callInfo)
	mock.lockGetHeaderClean.Unlock()
	return mock.GetHeaderCleanFunc(b)
}

// GetHeaderCleanCalls gets all the calls that were made to GetHeaderClean.
// Check the length with:
//
//	len(mockedTemplate.GetHeaderCleanCalls())
func (mock *TemplateMock) GetHeaderCleanCalls() []struct {
	B bool
} {
	var calls []struct {
		B bool
	}
	mock.lockGetHeaderClean.RLock()
	calls = mock.calls.GetHeaderClean
	mock.lockGetHeaderClean.RUnlock()
	return calls
}

// StartLine calls StartLineFunc.
func (mock *TemplateMock) StartLine() string {
	if mock.StartLineFunc == nil {
		panic("TemplateMock.StartLineFunc: method is nil but Template.StartLine was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStartLine.Lock()
	mock.calls.StartLine = append(mock.calls.StartLine, callInfo)
	mock.lockStartLine.Unlock()
	return mock.StartLineFunc()
}

// StartLineCalls gets all the calls that were made to StartLine.
// Check the length with:
//
//	len(mockedTemplate.StartLineCalls())
func (mock *TemplateMock) StartLineCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStartLine.RLock()
	calls = mock.calls.StartLine
	mock.lockStartLine.RUnlock()
	return calls
}
