// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
	"tail/internal/sink/console/template/general"
)

// Ensure, that IndicatorMock does implement general.Indicator.
// If this is not the case, regenerate this file with moq.
var _ general.Indicator = &IndicatorMock{}

// IndicatorMock is a mock implementation of general.Indicator.
//
//	func TestSomethingThatUsesIndicator(t *testing.T) {
//
//		// make and configure a mocked general.Indicator
//		mockedIndicator := &IndicatorMock{
//			CleanFunc: func(b bool) string {
//				panic("mock out the Clean method")
//			},
//			GetFunc: func() string {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedIndicator in code that requires general.Indicator
//		// and then make assertions.
//
//	}
type IndicatorMock struct {
	// CleanFunc mocks the Clean method.
	CleanFunc func(b bool) string

	// GetFunc mocks the Get method.
	GetFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Clean holds details about calls to the Clean method.
		Clean []struct {
			// B is the b argument value.
			B bool
		}
		// Get holds details about calls to the Get method.
		Get []struct {
		}
	}
	lockClean sync.RWMutex
	lockGet   sync.RWMutex
}

// Clean calls CleanFunc.
func (mock *IndicatorMock) Clean(b bool) string {
	if mock.CleanFunc == nil {
		panic("IndicatorMock.CleanFunc: method is nil but Indicator.Clean was just called")
	}
	callInfo := struct {
		B bool
	}{
		B: b,
	}
	mock.lockClean.Lock()
	mock.calls.Clean = append(mock.calls.Clean, callInfo)
	mock.lockClean.Unlock()
	return mock.CleanFunc(b)
}

// CleanCalls gets all the calls that were made to Clean.
// Check the length with:
//
//	len(mockedIndicator.CleanCalls())
func (mock *IndicatorMock) CleanCalls() []struct {
	B bool
} {
	var calls []struct {
		B bool
	}
	mock.lockClean.RLock()
	calls = mock.calls.Clean
	mock.lockClean.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *IndicatorMock) Get() string {
	if mock.GetFunc == nil {
		panic("IndicatorMock.GetFunc: method is nil but Indicator.Get was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc()
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedIndicator.GetCalls())
func (mock *IndicatorMock) GetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
