ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
  arguments = [["github.com/onsi/ginkgo/v2", "github.com/onsi/gomega"]]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]