name: Go Quality & Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Check Format (gofmt)
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            gofmt -d .
            exit 1
          fi

      - name: Install and Run Golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@master
          golangci-lint --config=.golangci.yml run ./...

      - name: Run Gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -quiet ./...

      - name: Go Mod Verify
        run: go mod verify

  unit-test:
    name: Unit Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Run Ginkgo Tests
        run: ginkgo -r ./...

  build:
    name: Build
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Build Application
        run: |
          mkdir -p app
          go build -ldflags='-w -s' -o ./app/app ./cmd/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-binary
          path: ./app/app